### ISSUE TITLE
Update boom to at least v.6 for vulnerability in hoek

### ISSUE THREAD

**Issue by phrred** [devinivy/waterline-to-boom#3]
HI, there is a vulnerability in hoek and that can be fixed by updating boom to at least version 6

https://nodesecurity.io/advisories/566   

Thanks

**Comment by devinivy** [comment]
Hey @phrred, I'm not maintaining this module anymore.  I would be happy to add you as a collaborator or transfer the repository to you if you'd like to address the necessary changes.
